### ISSUE TITLE
use goose instead of migrate

### ISSUE THREAD

**Issue by gedw99** [Baralga/baralga-app#53]
Hey,

Currently https://github.com/golang-migrate/migrate is used.

goose
https://github.com/pressly/goose
goose includes the drivers, plus handles db and go func migrations.

examples: https://github.com/pressly/goose/tree/master/examples

---

Current problems that goose removes.

No driver.
``` 
ake migrate.up
migrate -path /Users/apple/workspace/go/src/github.com/gedw99/sc-gio/pomodoro/exp/baralga__baralga-app/baralga-app/shared/migrations -database "postgres://postgres:postgres@localhost:5432/baralga?sslmode=disable" up
error: database driver: unknown driver postgres (forgotten import?)
```

**Comment by remast** [comment]
I think the current implementation should work fine when calling _make migrate.up_.

Or just start the app on an empty schema and it will migrate automatically.

**Comment by gedw99** [comment]
Yeah it's fine - was just an idea for ease of use.

Can you tell me then how i can run the migration from outside docker ?

I just did a go install of the migrate package, but it seems it does not include drivers for postgresql.

I am getting on **make migrate.up**
``` 
error: database driver: unknown driver postgres (forgotten import?)
```
I could not see any pointers on migrate site

**Comment by remast** [comment]
I tested the migration from the command line on Mac and that worked for me. So I used the CLI version of `migrate` installed using `brew install golang-migrate`.

**Comment by gedw99** [comment]
Ah I used go install.

I wanted to do it this way to make CI is independent.
